import type { APIRoute } from 'astro';
import { QR_TYPES } from '../lib/payloads';
import { getUi } from '../lib/i18n';
import { REPO_URL } from '../lib/site';

/**
 * The one honest machine interface this site has: GET a page with query
 * parameters and the generator opens prefilled. Nothing is generated
 * server-side and nothing is downloaded without a click.
 */
export const GET: APIRoute = ({ site }) => {
  const origin = (site ?? new URL('https://justgivemetheqr.com')).origin;
  const ui = getUi('en');

  const paths: Record<string, unknown> = {};
  for (const type of QR_TYPES) {
    const parameters = type.fields.map((field) => ({
      name: field.name,
      in: 'query',
      required: false,
      description:
        `${field.label}.` +
        (field.help ? ` ${field.help}` : '') +
        (field.aliases?.length ? ` Aliases: ${field.aliases.join(', ')}.` : '') +
        (field.options ? ` One of: ${field.options.map((o) => o.value).join(', ')}.` : ''),
      schema:
        field.kind === 'checkbox'
          ? { type: 'boolean' }
          : field.options
            ? { type: 'string', enum: field.options.map((o) => o.value) }
            : { type: 'string' },
    }));
    if (type.id === 'url') {
      parameters.push({
        name: 'type',
        in: 'query',
        required: false,
        description: 'Preselect a content type on the home page instead of visiting its own page.',
        schema: { type: 'string', enum: QR_TYPES.map((t) => t.id) },
      });
    }
    paths[type.path] = {
      get: {
        operationId: `open${type.id.charAt(0).toUpperCase()}${type.id.slice(1)}Generator`,
        summary: `Open the ${ui.types[type.id] ?? type.label} QR generator, optionally prefilled`,
        description:
          `Returns the HTML page for the ${ui.types[type.id] ?? type.label} QR code generator. ` +
          'Any query parameter listed here prefills the matching field; the QR code is then rendered in the visitor\'s browser. ' +
          'Nothing is stored or downloaded automatically. This is a page for a person to open, not an image endpoint.',
        parameters,
        responses: {
          '200': { description: 'The generator page, prefilled.', content: { 'text/html': { schema: { type: 'string' } } } },
          '404': {
            description: 'No such page. The site is static, so this is a plain HTML 404 with links to the sitemap and llms.txt.',
            content: { 'text/html': { schema: { type: 'string' } } },
          },
        },
      },
    };
  }

  const doc = {
    openapi: '3.1.0',
    info: {
      title: 'Just Give Me The QR — prefill links',
      version: '1.0.0',
      summary: 'How to link into a free, browser-only QR code generator with fields already filled in.',
      description:
        'This site has no server-side API. QR codes are generated by JavaScript in the browser and never uploaded. ' +
        'What it does offer is a stable link format: every generator page accepts its fields as query parameters, ' +
        'so an agent can build a link that opens the generator ready to download. There are no error responses, ' +
        'no authentication and no rate limits, because there is nothing but static files.',
      license: { name: 'Source available', url: REPO_URL },
      'x-stability':
        'Field names are the ones shown in each form and are meant to be permanent; aliases exist so short links keep working. ' +
        'There is no versioned path because nothing here is an API that can break: a link that worked once keeps working. ' +
        'Any change would be announced in the repository first.',
    },
    servers: [{ url: origin }],
    paths,
  };

  return new Response(JSON.stringify(doc, null, 2), { headers: { 'Content-Type': 'application/json; charset=utf-8' } });
};
